
name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable
        run: echo "API_KEY=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" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JavaScript code
        run: node gptTurbo.js
